name: publish
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Push events to matching *, i.e. 1.0, 20.15.10
      - "v[0-9]+.[0-9]+.[0-9]+-rc*" # Push events to matching *rc*, i.e. v1.0-rc1, v20.15.10-rc5
      - "v[0-9]+.[0-9]+.[0-9]+-beta*" # Push events to matching *b*, i.e. v1.0-beta1, v20.15.10-beta5

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        poetry-version: ['1.1.10']
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: poetry-check
        run: poetry check
      - name: poetry-build
        run: poetry build
      - name: poetry-publish
        if: matrix.python-version == '3.10'
        run: poetry publish --build --username __token__ --password ${{ secrets.PYPI_TOKEN }}
